### PR TITLE
Introduce rollup

### PR DESCRIPTION
**Pull request by CarstenWickner**
This looks promising in the respect that it reduces the standard CommonJS bundle from 74 KB to 57 KB without loss of functionality.

However, I still don't understand how consumers of this component would make sure they actually use the minified version.
Till now, the webpack configuration was only generating a single minified bundle.
Doing it via rollup would also be an option, but since I don't really understand the benefits of also exporting an ES Module (which is even smaller with 47 KB) I'm hesitant.

@jeniamoroz maybe you can help me understand what a good course of action would be here.

### CODE REVIEW

**Comment by CarstenWickner** [comment]
Alright, I can understand exporting only a single target bundle and since this is a react component, the ES module seems the most appropriate – minified to reduce its size since that should be the desired type of bundle for "normal" usage.

In regards to exact dependency versions. Would you apply that only to the actual "dependencies" or also to "devDependencies" or even "peerDependencies"?

**Comment by jeniamoroz** [comment]
for all but peerDependencies

**Comment by CarstenWickner** [comment]
Would you reckon fixing it via a "package-lock.json" would be the right way to go?
Fixing it in the "package.json" here (i.e. in this library) sounds like it might lead to duplicated dependencies for whoever is using it and happens to require a different (compatible) version of the same dependency.

Using something like https://greenkeeper.io would still allow for the dependency range to be corrected in a timely fashion if there is a breaking issue with one of the dependencies.

**Comment by jeniamoroz** [comment]
Yes, it might lead to duplicates for consumer, but also can do so if you keep ^ notation. I don’t see this as big issue. Yes, you would need to update package-lock.json, but it won’t affect whoever is using the library (as far as I remember).
About gatekeeper, haven’t tried it yet, don’t think there is a need for it. Heard about “dependabot” though, which soon should be part of github.
Anyways, I would leave changes of package.json to a separate PR.

**Comment by CarstenWickner** [comment]
@jeniamoroz thank you very much for your input!

Just to respond to your last comment:
- "dependabot" checks for known security vulnerabilities or other out-of-date scenarios and creates automatic PRs to upgrade the dependencies when necessary. That's already enabled (at least for resolving security issues).
- "Greenkeeper" is executing a CI build each time it detects a new in-range dependency version. If that CI build is broken due to a new dependency release, it creates automatic PRs to lock the dependency version down to avoid the buggy version from being used. I'm enabling that one as well now to cover both scenarios.

**Pull request merged**
